### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by santisoler** [santisoler/website#1]

**Comment by santisoler** [comment]
Add badges for Travis CI and website status.

**Comment by santisoler** [comment]
Add tutorial on how to build and serve the website.

**Comment by santisoler** [comment]
Add tutorial on how to properly add a Travis deployment?

**Comment by santisoler** [comment]
Add a reference to @leouieda's website, which have served as inspiration.

**Comment by leouieda** [comment]
:+1: website looks good!

**Comment by santisoler** [comment]
Thanks @leouieda! I've started from Urubu's Quickstart, but I think you noticed the influence of your website haha.
I've also had inspiration from @lheagy's website, I like how her single page design shows a lot of information in just a few scrolls.

**Comment by leouieda** [comment]
Not really, actually. I actually thought of borrowing some of your home page design :)

**Comment by santisoler** [comment]
Feel free to do it! I think the templates for the home elements can be improved. They are quite a little hard to read, but at least they are working. As I pointed on  #21 I'd like to set a max number of elements per section (e.g. show only the last four papers, or maybe pinned papers) and a "Read more" link at the bottom. That would unclutter the home page when a section has too much of content.

**Comment by leouieda** [comment]
I've certainly spent way too much playing with Jinja but the templating is a lot of fun. It's amazing what you can do with Jinja and the reason I like Urubu over Pelican et al.

**Comment by lheagy** [comment]
Your site is beautiful! So the inspiration goes both ways :)

**Comment by santisoler** [comment]
> Your site is beautiful! So the inspiration goes both ways :)

Thanks @lheagy! I'm glad it can serve as inspiration for others.

**Comment by santisoler** [comment]
> I've certainly spent way too much playing with Jinja but the templating is a lot of fun. It's amazing what you can do with Jinja and the reason I like Urubu over Pelican et al.

You're right @leouieda, Jinja offers a lot of possibilities. I opted for Urubu because I've already had some knowledge on Bootstrap, so I wanted to make use of it. I haven't tried Pelican besides serving the example site, but searching "bootstrap" on its documentation gives no match. That was a bummer taking into account my tiny background on web development. On the other hand, Urubu welcomes Bootstrap from the beginning.
Maybe a drawback of Urubu is it only supports Bootstrap 3 (for now at least). Would be nice to extend the support for Bootstrap 4, what will eventually be the standard. Maybe opening an issue on Urubu's repo would be a good idea.

**Comment by leouieda** [comment]
Well, you have full control of all of the templates in Urubu. So if you want bootstrap 4 you can update it in your base template.

**Comment by santisoler** [comment]
Maybe I'll try it in the future. I think it could be fast and easy or it could take more work in case there are a lot of little things that must be changed.
